######################################################################
# Automatically generated by qmake (3.0) Fri Oct 31 13:01:50 2014
######################################################################

TEMPLATE = app
TARGET = matrix-multiply
INCLUDEPATH += .

# Input
HEADERS += argumentlist.h QStreamThreaded.h
SOURCES += argumentlist.cpp matrix-multiply.cpp QStreamThreaded.cpp
